export const PRODUCTS = [
    {
      id: 1,
      productName: 'GTA 5 PS5 (Grand Theft Auto)',
      price: 28000,
      category: 'Adventure',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2022/04/GTA-5-PS5-474x600-1.webp',
    },
    {
      id: 2,
      productName: 'FIFA 23 PS5',
      price: 41000,
      category: 'Sport',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2022/09/FIFA-23-PS5-479x600-2.webp',
    },
    {
      id: 3,
      productName: 'God of War Ragnarok PS5',
      price: 60000,
      category: 'Adventure',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2022/11/God-of-War-Ragnarok-PS5-468x600-1.webp',
    },
    {
      id: 4,
      productName: 'Call of Duty: Modern Warfare III Xbox Series X',
      price: 72000,
      category: 'Shooter',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2023/10/Call-of-Duty-Modern-Warfare-XSX-463x600-1.webp',
    },
    {
      id: 5,
      productName: 'Need For Speed Unbound Xbox Series X',
      price: 51000,
      category: 'Racing',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2022/11/NFS-Unbound-XSX-487x600-1.webp',
    },
    {
      id: 6,
      productName: 'Gran Turismo 7 PS5',
      price: 60000,
      category: 'Racing',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2022/01/Gran-Turismo-7-PS5-474x600-1.webp',
    },
    {
      id: 7,
      productName: 'EA Sports FC Xbox Series X and Xbox One',
      price: 67000,
      category: 'Sport',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2023/07/EA-Sports-FC-24-XSX-487x600-1.webp',
    },
    {
      id: 8,
      productName: 'Far Cry 6 PS5',
      price: 30000,
      category: 'Adventure',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2021/09/Far-Cry-6-PS5-480x600-WEB.webp',
    },
    {
      id: 9,
      productName: 'A Plague Tale Requiem Xbox Series X',
      price: 36000,
      category: 'Adventure',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2023/07/A-Plague-Tale-Requiem-XSX-461x600-1.webp',
    },
    {
      id: 10,
      productName: "The Callisto Protocol Xbox Series X",
      price: 43000,
      category: 'Adventure',
      productImage: 'https://www.vgstores.ng/wp-content/uploads/2023/07/The-Callisto-Protocol-XSX-462x600-1.webp',
    },
    {
      id: 11,
      productName: "NBA 2K23 PS5",
      price: 37000,
      category: "Sport",
      productImage: "https://www.vgstores.ng/wp-content/uploads/2022/09/NBA-2K23-PS5-470x600-1.webp",
      },
    {
      id: 12,
      productName: "Spider Man Miles Morales PS5",
      price: 36000,
      category: "Adventure",
      productImage: "https://www.vgstores.ng/wp-content/uploads/2021/01/Spider-Man-Miles-Morales-PS5-468x600-1.webp",
    },
  ];
  
